services:
  frontend:
    image: httpd:latest
    container_name: frontend
    ports:
      - "5000:80"
    volumes:
      - ./front-end:/usr/local/apache2/htdocs/
    networks:
      - frontend
    depends_on:
      - backend

  backend:
    image: ranaahmed2/flask-app:0.6
    container_name: back-end
    networks:
      - frontend
      - backend
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: maria-db
    environment:
      - MARIADB_ROOT_PASSWORD=01098737226
    networks:
      - backend

networks:
  frontend:
  backend:
